### ISSUE TITLE
Cleanup Reward Page and Character.js code

### ISSUE THREAD

**Issue by nikothomas** [cse110-sp24-group19/final-project#120]
### Task Description

**Description:**
reward-page.js has testing code that gives you progression points for clicking on the screen, as well as testing code to create a character without user input. Character.js still has a "TBD" character.

**Related User Story:**
I am a work journal user and I want my progression to reflect my actual work, and for my characters to display properly on screen.

### Sub-tasks

- [x] Cleanup reward-page.js
- [x] Cleanup character.js
- [x] Ensure no unused/test code is still lying around

### Estimated Effort
Low

### Priority
Medium

### Dependencies
A new character to fill in TBD or a group decision to only have Monkey and Dragon characters. 
A choose your character screen.

### Assignees
@nikothomas

### Labels
Sprint 2
Medium Priority

**Comment by nikothomas** [comment]
Character "TBD" has been removed
