### ISSUE TITLE
Set up the "Choose Your Character" View

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#141]
### Set up the "Choose Your Character" View

**Description:**
Create a new view on the reward page to be able to choose your character

**Related User Story:**
Character Reward System
User Story: 
As a young adult, I want to level up with characters in order to feel rewarded and motivated to work on my goals.

### Sub-tasks

- [ ] Create the view
- [ ] Set up a selection process
- [ ] Make sure it only shows up once

### Estimated Effort
Medium effort ~ a couple hours

### Priority
High

### Assignees
@Julie827
