### ISSUE TITLE
Add TODAY button to navigate back to today in the Calendar View

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#142]
### Task Description

**Description:**
Add a button in the top right that just says "Today" and when you click on it, it should reload the calendar view to go back to today.

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [ ] Create the button and style it (make sure it is responsive)
- [ ] Set up navigation function
- [ ] Make button functional

### Estimated Effort
Low ~ 30 min

### Priority
Low

### Assignees
@jrivas112

**Comment by jrivas112** [comment]
Finished, added the Today Button

Note: 
Because the pages are all in the same HTML file, we have to essentially go through the same process that the page goes through when it first loads, it hides all the pages besides the main-page. However, when we use the Today Button it will hide all the pages (including main) and just expose the calendar instead
