### ISSUE TITLE
Update Styling for Calendar Header

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#156]
### Task Description

**Description:**
Make sure that the calendar header looks good on mobile view and that the month/year text is resizable. The search button should have the same styling as the "Today" button.

### Sub-tasks

- [ ] Update CSS for header text
- [ ] Make Search Button look the same as the Today button
- [ ] Update CSS so that things look good on a mobile view

### Estimated Effort
Low ~ 1 hour

### Priority
Medium

### Additional Information
![image](https://github.com/cse110-sp24-group19/final-project/assets/40010548/cebc75be-70f4-4dcb-9e02-7703dc45ae8f)

### Assignees
@milgor931
