### ISSUE TITLE
REPO CLEANUP TASK: Set up a src directory and get rid of dups (aka out vs docs)

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#170]
### Task Description

**Description:**
Set up a src directory and get rid of extra and unused folders (aka out vs docs). Put the assets folder in src and capitalize all the *.md files

### Sub-tasks

- [ ] Move webapp stuff to src directory (NOT THE index.HTML)
- [ ] Update all file paths where appropriate
- [x] Capitalize all of the *.md files
- [ ] Update affected GitHub actions
- [x] Delete out folder
- [ ] #216
### Estimated Effort
Medium

### Priority
Low
