### ISSUE TITLE
Reward Page Styling Fixes

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#171]
### Task Description

**Description:**
Add numerical value to the slider and left align or otherwise straighten text. 
Avoid centering but if we do center, then make the text bigger
The gear icon on the reward page should be in the bottom right and smaller.

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [x] Add numerical value to the slider and left align or otherwise straighten text. 
- [x] Avoid centering but if we do center, then make the text bigger
- [X] The gear icon on the reward page should be in the bottom right and smaller.

### Estimated Effort
Low

### Priority
High
