### ISSUE TITLE
Set up Intro View to Rewards Page

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#173]
### Task Description

**Description:**
Upon first entry of the rewards page, set up a custom view to pick your character!

**Related User Story:**
Character Reward System
User Story: 
As a young adult, I want to level up with characters in order to feel rewarded and motivated to work on my goals.

### Sub-tasks

- [x] Set up the new view
- [x] Set up local storage to initialize new character
- [x] Form to pick character
- [x] Save character to local storage

### Estimated Effort
High

### Priority
High

**Comment by nikothomas** [comment]
Pull #180 addresses this, just need to add monkey images

**Comment by nikothomas** [comment]
Finalized with pull #194
