### ISSUE TITLE
Final Public Video 

### ISSUE THREAD

**Issue by rianaali** [cse110-sp24-group19/final-project#217]
### Task Description

**Description:**

Assignees feel free to be creative and fun with this!! Subtasks list who is assigned to each clip, its time limit, and whats its content should be.
Per Kashish's announcement: " The class is over and it is time to show the world what you have done. We don't have a lot of time in our final exam period, but we have time to show around 3mins of a video (+/- 30seconds) that can let everyone know what you did and how well your project went.  For bragging rights and sharing lessons learned produce a video no longer than 3:30s and no shorter than 2:00s."

**Related User Story:**

### Sub-tasks
- [x] ** someone and Mark -** **Time Limit 30 seconds** - Team Name and Number & Brief mention on video or with a picture of each member and their role(s)
- [x] **Julie -** **Time Limit 2 minutes** - A quick tour of your product (make that part sizzle to show off any features or things you are proud of)
- [x] **Milana - Time Limit 30 Seconds** - A brief retrospective of what challenges you faced, what things you felt you overcame and anything you feel you would do differently now that you are done
- [x] **Ginger -** **Time Limit 30 seconds** Conclude your video with a brief point of advice for the next students (victims) of 110 projects so they crush the project

### Estimated Effort

Medium-High

### Priority

High

### Assignees

@milgor931
@Julie827
@rianaali 
@Markcmd 
@gingersmith4
