### ISSUE TITLE
Final Private Video

### ISSUE THREAD

**Issue by rianaali** [cse110-sp24-group19/final-project#218]
### Task Description

**Description:**

**Everyone must submit a clip for this video BY SUNDAY 11:59** (check subtasks). This video is professional, and less creative than the public video. Subtasks list who is assigned to each clip, its time limit, and whats its content should be.
Per Kashish's announcement: "The class is over and it is time to hand-off our work to others and have an honest look at what we did well and not so well in our Agile development practices. To communicate information both to the graders and to a person who might take over your project at a future date you should make a video (shorter than 12 minutes, and longer than 6 minutes) to help us understand your project, pipeline, and team effort. This video does not have to be fancy or polished, but it might be wise to at least have a nice title and conclusion section for presentation consistency."

**Related User Story:**

### Sub-tasks

- [x] **EVERYONE - Time Limit 35 seconds each (but should be ~30 seconds)** - Each team member should be present and in their own words state what they did on the project, what they are proud of and what they feel they could improve upon or address beyond the class (totals to 5.5 to 6.5 minutes)
- [X] **Mark and Julie - Time Limit 10 seconds -**  Team Name and Number 
- [X] **Julie - Time Limit 2 minutes 50 seconds -** A video discussion about how to access your repo, a tour of the repo organization and a demonstration of making a small change to the repo and the completion of the build process. You may need to write more detailed discussion of building or onboarding the product than the video supports. If so create a markdown file called "onboard.md" and put it in your documentation which goes into more details.
- [x] **Riana - 40 seconds -** A video goring through the README file and user manual. 
- [x] **Milana - Time Limit 2 minutes -** 
A more involved retrospective about how your Agile practices were conducted and what challenges and victories the team faced. Honesty is the best course of action here as we are more likely to be lenient if we understand you are aware of what you didn't do well on the project and practices.
Conclude your video with a discussion of what things a team taking on your project should do next. Discuss the features not built yet, improvements to the build pipeline or anything else you would have gotten to given another quarter worth of work.

### Estimated Effort

Medium-High

### Priority

High

### Assignees

@nikothomas 
@jrivas112 
@Markcmd 
@milgor931 
@Julie827 
@a4lane 
@bpanuco11 
@jrivas112 
@ddesantiag0 
@gingersmith4 
@Charlitoes
