### ISSUE TITLE
Creative Play Page

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#24]
### Task Description

**Description:**
Use p5.js to create an embedded whiteboard in the page --> add text and draw

**Related User Story:**
Brainstorm/Freewrite/Creative Play Functionality
User Story: As a young adult , I want to be able to brainstorm and doodle ideas for what I can work on in order to visualize my thoughts and tap into my creativity.

### Sub-tasks

- [ ] Set up p5.js
- [ ] Create whiteboard canvas
- [ ] Add color change controls
- [ ] Add eraser and clear option
- [ ] Add option to change pen size

### Estimated Effort
High

### Priority
Medium

### Dependencies
Need to import p5.js

### Assignees
@milgor931
