### ISSUE TITLE
Goal-Setting Page ~ edit, delete, add task feature

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#28]
### Task Description

**Description:**
Set up the goal-setting page

**Related User Story:**
Goal-Setting
User Story: As a young adult, I want to set goals in order to achieve my biggest dreams in life. 

### Sub-tasks

- [x] Create a goal-setting page where the user can set goals for today, this week, and long-term.
- [x] Set up a system to create goals

### Estimated Effort
Medium

### Priority
Medium

### Assignees
@a4lane 
@gingersmith4

**Comment by gingersmith4** [comment]
Modify styling so the blocks don't move when you hover over them, the one you're hovering over just gets a thicker outline

**Comment by gingersmith4** [comment]
Ginger to-dos

- [ ] write function for editing a goal
- [ ] write function for deleting a goal
- [ ] coordinate testing for these functions - maybe with Riana who is using puppeteer
