### ISSUE TITLE
Set Up Search/Filtration System for Calendar View

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#31]
### Task Description

**Description:**
Set up search and filter system for the calendar view

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [x] Set up backend logic to search journal entry data
- [x] Set up the UI
- [x] Get the journal entries to populate the UI properly
- [x] Make sure stickers are displayed in chronological order

### Estimated Effort
High ~ several hours

### Priority
High

### Assignees
@Markcmd 
@bpanuco11
