### ISSUE TITLE
Set up Labeling Feature for Journal Entries

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#32]
### Task Description

**Description:**
Be able to create, delete, and edit labels.

Labels should have a text and color associated with them and can be added to tasks or journal entries

**Related User Story:**
Journaling 
User Story: As a young adult, I want to journal my thoughts, achievements, and goals in order to reflect on my progress, write down my ideas for creative work, and develop my character.

### Sub-tasks

- [ ] Be able to create label (color, name)
- [ ] Be able to edit label (color, name)
- [ ] Make sure journal entries are properly updated

### Estimated Effort
High

### Priority
Medium

### Assignees
@ddesantiag0 
@bpanuco11

**Comment by milgor931** [comment]
Closed because we didn't have enough time to implement this. ADR should mention more details.
