### ISSUE TITLE
Enhance Calendar View

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#33]
### Task Description

**Description:**
Enhance calendar view to look like Nik's design with stickers and add clickable functionality to navigate to the journal edit page

**Related User Story:**
Journaling 
User Story: As a young adult, I want to journal my thoughts, achievements, and goals in order to reflect on my progress, write down my ideas for creative work, and develop my character.

### Sub-tasks

- [ ] Update the page so that the date items are stickers
- [ ] If you click on a date sticker, the journal entries for that date in the labeled color should appear.
- [ ] You should be able to click a button to navigate to that journal entry to edit
- [ ] Add button to edit, delete, or add journal entry

### Estimated Effort
High

### Priority
High

### Assignees
@jrivas112

**Comment by milgor931** [comment]
Calendar view is enhanced!
