### ISSUE TITLE
Create Puppeteer Tests for Webpage and for Backend Logic

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#34]
### Task Description

**Description:**
Set up tests for logic testing

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [ ] Add puppeteer tests to make sure buttons + navigation system works well
- [ ] Add Jest tests to make sure functions work properly 
- [ ] Add tests to make sure level up progression work properly

### Estimated Effort
High

### Priority
High

### Assignees
@rianaali
