### ISSUE TITLE
Create Characters

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#43]
### Task Description

**Description:**
Create at least 3 characters to be used for the level-up feature

**Related User Story:**
Character Reward System

User Story: 
As a young adult, I want to level up with characters in order to feel rewarded and motivated to work on my goals.

### Sub-tasks

- [x] Create baby level 1 character
- [x] Create level 2 intermediate character
- [x] Create level 3 high level character

### Estimated Effort
Medium

### Priority
Low

### Dependencies
n/a

### Additional Information
n/a

### Assignees
@nikothomas 
@Markcmd

**Comment by Charlitoes** [comment]
PR #204 adds the rest of the character images
