### ISSUE TITLE
Set Up Home Page + Navigation Menu

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#44]
### Task Description

**Description:**
Set up home page navigation and view

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [x] Set up home page
- [x] Set up navigation bar for every page
- [ ] Embed character into home page

### Estimated Effort
High

### Priority
High

### Dependencies
Characters have been created and other HTML webpages can be routed to

### Assignees

@Julie110 
@gingersmith4

**Comment by Julie827** [comment]
Main page is done!
