### ISSUE TITLE
Add Level-Up Backend

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#45]
### Task Description

**Description:**
Add backend logic for leveling up the characters

**Related User Story:**
Character Reward System
User Story: 
As a young adult, I want to level up with characters in order to feel rewarded and motivated to work on my goals.

### Sub-tasks

- [ ] User earns 1 point for each day they log on, and for each task they complete
- [ ] Points for goal completion TBD
- [ ] First character level-up occurs when 10 pts have been accumulated, each successive level-up increments cost by 5 pts
- [ ] Progressions happen automatically when enough points have been accumulated

### Estimated Effort
Medium

### Priority
Medium

### Assignees
@a4lane

**Comment by nikothomas** [comment]
Character.js provides some of these components, jsdoc examples need updating though:

-  First character level-up occurs when 10 pts have been accumulated, each successive level-up increments cost by 5 pts
-  Progressions happen automatically when enough points have been accumulated
