### ISSUE TITLE
Create Journal Entry Edit Page

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#47]
### Task Description

**Description:**
Create the journal entry edit page

**Related User Story:**
Journaling 
User Story: As a young adult, I want to journal my thoughts, achievements, and goals in order to reflect on my progress, write down my ideas for creative work, and develop my character.

### Sub-tasks

- [ ] Create form for the journal edit page
- [ ] Auto-populate the date
- [ ] Set up title 
- [ ] Be able to apply labels
- [ ] Save and delete buttons

### Estimated Effort
High

### Priority
High

### Assignees
@milgor931
