### ISSUE TITLE
Design and Create the Reward Page

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#92]
### Task Description

**Description:**
Design a reward page and code it. It should display the character you are currently at, your stats (how many log ons, tasks completed).

**Related User Story:**
Character Reward System
User Story: 
As a young adult, I want to level up with characters in order to feel rewarded and motivated to work on my goals.

### Sub-tasks

- [ ] Design the reward page and add it to the Miro Board
- [ ] Add in a character display
- [ ] Track and display stats using local storage

### Estimated Effort
Medium effort

### Priority
Medium

### Assignees
TBD
